### PR TITLE
Make `setup.py` consistent with conda recipe

### PR DESCRIPTION
**Pull request by xylar**
Inconsistencies in `setup.py` can cause `pip check` to fail on the conda package.

### CODE REVIEW

**Comment by xylar** [comment]
@tomvothecoder, could we get hellp on why CI is failing?

**Comment by tomvothecoder** [comment]
@xylar The `pre-commit-hooks` job is now fixed (bumped `isort` to latest version and bumped other things just to make sure they are up to date).

**Comment by forsyth2** [comment]
I was able to build the environment with this branch. I'm still running the tests however -- considering I found an error on the test step for https://github.com/E3SM-Project/zstash/pull/250, I'll wait to merge this until I can make sure the tests pass.

**Comment by forsyth2** [comment]
Tests pass, merging.

**Pull request merged**
