### PR TITLE
Fix ylim

### LINKED ISSUE #177: Fix bad plot formatting in global time series
Some global time series plots (https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.golaz/E3SMv2/v2.NARRM.1pctCO2_0101/global_time_series/global_time_series_0001-0150_results/v2_1pctCO2_0101.png, https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.golaz/E3SMv2/v2.NARRM.abrupt-4xCO2_0101/global_time_series/global_time_series_0001-0150_results/v2_abrupt-4xCO2_0101.png) are poorly formatted.

This may be due to an error with out the y-limit is set.

### PR DESCRIPTION
**Pull request by forsyth2**
Fix `ylim` in global time series. Resolves #177.

### CODE REVIEW

**Review by golaz — APPROVED** [review]
@forsyth2 : thanks for implementing this. This should solve the problem.

**Comment by forsyth2** [comment]
Unfortunately, this fix seems to distort the plots that worked fine before. From the integration tests (https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.forsyth2/zppy_test_complete_run_www/image_check_failures_20220128/):

Actual:
image

Expected:
image

**Comment by forsyth2** [comment]
@golaz Plots 2 and 3 look the most distorted above. I've listed the "standard" ranges below -- perhaps some of those ranges should be changed? Or alternatively, perhaps the graph minimum should also change to the value minimum if the value maximum exceeds the "standard" range (rather than just changing the graph maximum)?

The current "standard" ranges are:
1. Net TOA flux (restom) [-1.5, 1.5]
2. Global surface air temperature [-1.5, 1.5]
3. TOA radiation: SW (solid), LW (dashed) [-1.5, 1.5]
4. Net atm energy imbalance (restom-ressurf) [-0.3, 0.3]
5. Change in ocean heat content [-0.3e24, 0.9e24]
6. Max MOC Atlantic streamfunction at 26.5N [4, 22]
7. Change in sea level [4, 22]
8. Net atm water imbalance (evap-prec) [-1, 1]

**Comment by forsyth2** [comment]
I assumed the `ylim` of `[-1.5., 1.5]` from plot 1 was also used for plots 2 and 3. However, each plot starts with a new `ax`, so since plots 2 and 3 didn't specify `ylim`, they actually just didn't have a standard range.

**Comment by forsyth2** [comment]
I think `[12,15]` and `[240, 245]` are ok "standard" ranges for `ylim` on plots 2 and 3 respectively:

image

**Pull request merged**
