### PR TITLE
Include MPAS-Analysis ncclimo options in zppy config

### PR DESCRIPTION
**Pull request by xylar**
Users may wish (or need) to change these config options in order for `ncclimo` to work for large MPAS-Ocean and -Seaice meshes.

Related to #9

### CODE REVIEW

**Review by golaz — APPROVED** [review]

**Comment by xylar** [comment]
@forsyth2, please don't merge this PR until after #63.  Otherwise, you will also merge #63, maybe without meaning to.

**Comment by xylar** [comment]
@forsyth2, these commits cannot be squashed.  Rather, the first commit is he only commit from #63.  This PR branched off from #63 because it would otherwise conflict with it.  So to have this PR have a clean commit history, you need to merge #63, then I need o rebase this onto the new `main`, then you can merge this (which will now have a single commit in the PR).  Alternatively, we can live with the fact that the commit from #63 is also listed in this PR.  That will speed up the process but leave GitHub a little less tidy.

**Comment by forsyth2** [comment]
@xylar I just merged #63, so you're good to squash these commits and merge. Thanks!

**Comment by xylar** [comment]
@forsyth2, okay, rebased!

**Review by forsyth2 — APPROVED** [review]

**Pull request merged**
