### PR TITLE
Update diags defaults

### PR DESCRIPTION
**Pull request by forsyth2**
Update diags defaults. Addresses the first item of #454 ("update existing campaigns by adding new defaults e3sm_diags sets")

### CODE REVIEW

**Comment by forsyth2** [comment]
Defaults after this pull request merges:

|sets|default.ini|cryosphere|high_res_v1|water_cycle|
|---|---|---|---|---|
|aerosol_aeronet|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|
|aerosol_budget|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|
|area_mean_time_series| | | | |
|annual_cycle_zonal_mean|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|
|cosp_histogram|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|
|diurnal_cycle| |:heavy_check_mark:| |:heavy_check_mark:|
|enso_diags| |:heavy_check_mark:| |:heavy_check_mark:|
|lat_lon|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|
|meridional_mean_2d|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|
|polar|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|
|qbo| |:heavy_check_mark:| |:heavy_check_mark:|
|streamflow| |:heavy_check_mark:| |:heavy_check_mark:|
|tc_analysis| | | | |
|zonal_mean_2d|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|
|zonal_mean_2d_stratosphere|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|
|zonal_mean_xy|:heavy_check_mark:|:heavy_check_mark:| |:heavy_check_mark:|

**Comment by chengzhuzhang** [comment]
Thanks @mahf708 ! It would be nice to revert the changes, to bring the familiar order back..

**Comment by forsyth2** [comment]
Did we just want to put `lat_lon` first or revert the entire commit? E3SM Diags has a lot of sets now and I think it really improves readability/usability to have them listed (at least mostly) alphabetical. For instance, it makes it much easier to quickly see if you're including all the sets you wanted to.

**Comment by chengzhuzhang** [comment]
My preference would be to revert to previous order. The idea is that core sets are listed before specialized sets. And we want to make the list relatively permanent, and appending new sets when they become available. @forsyth2 could you fix this? Maybe we can patch the conda-forge release for this change.

**Comment by forsyth2** [comment]
> could you fix this?

#521 

> Maybe we can patch the conda-forge release for this change.

You mean include it in the upcoming E3SM Unified patch release? (Along with https://github.com/E3SM-Project/zstash/pull/304)

**Pull request merged**
