### PR TITLE
Add high resolution support

### LINKED ISSUE #131: Support High-Resolution simulations
Enable `zppy` time series and climatologies for high resolution model output. It should work for cori-knl and cori-haswell.

### PR DESCRIPTION
**Pull request by forsyth2**
Add high resolution support. Resolves #131.

### CODE REVIEW

**Comment by forsyth2** [comment]
@golaz This is ready for review. Note that this only enables support for `climo` and `ts`.

I ran on low-res data and on hi-res data. All jobs completed with "OK" status

Hi-res config file:
```
[default]
machine = 'cori-haswell'
environment_commands = "export PATH=/global/homes/z/zender/bin_cori:${PATH}"
walltime = "8:00:00"
input = /global/cfs/cdirs/e3smdata/simulations/20190910.branch_noCNT.n825def.unc06.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG
input_subdir = archive/atm/hist
output = /global/cscratch1/sd/forsyth/zppy_development/issue_131.20190910.branch_noCNT.n825def.unc06.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG
case = theta.20190910.branch_noCNT.n825def.unc06.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG
www = /global/cfs/cdirs/e3sm/www/forsyth/zppy_development/issue_131
partition = haswell
e3sm_unified = latest

[climo]
active = True
walltime = "8:00:00"
years = "056-057",

  [[ atm_monthly_720x1440_nco ]]
  input_files = "cam.h0"
  mapping_file = /global/cfs/cdirs/e3sm/zender/maps/map_ne120np4_to_cmip6_720x1440_aave.20181001.nc

[ts]
active = True
years = "056:057:1",

  [[ atm_monthly_720x1440_nco ]]
  input_files = "cam.h0"
  mapping_file = /global/cfs/cdirs/e3sm/zender/maps/map_ne120np4_to_cmip6_720x1440_aave.20181001.nc
  vars = "FSNTOA,FLUT,FSNT,FLNT,FSNS,FLNS,SHFLX,QFLX,TAUX,TAUY,PRECC,PRECL,PRECSC,PRECSL,TS,TREFHT,CLDTOT,CLDHGH,CLDMED,CLDLOW"

  [[ atm_monthly_glb ]]
  input_files = "cam.h0"
  mapping_file = "glb"
  vars = "FSNTOA,FLUT,FSNT,FLNT,FSNS,FLNS,SHFLX,QFLX,TAUX,TAUY,PRECC,PRECL,PRECSC,PRECSL,TS,TREFHT,CLDTOT,CLDHGH,CLDMED,CLDLOW"

[glb]
active = False

[e3sm_diags]
active = False

[e3sm_diags_vs_model]
active = False

[amwg]
active = False

[mpas_analysis]
active = False

[global_time_series]
active = False
```

**Comment by forsyth2** [comment]
@ndk @czender This pull request resolves #131, although only for the `climo` and `ts` tasks.

**Comment by czender** [comment]
The PR looks good to me. It is necessary as is for HR data. Once we shift to the next E3SMU, which will contain NCO 5.0.2, the --mem_mb=0 options will no longer be necessary in zppy because NCO will default to that setting.

**Review by golaz — APPROVED** [review]
Changes look good to me. It's good that we don't need a HR specific flag.

**Comment by forsyth2** [comment]
Merged. Still need to update the expected files for the `zppy/tests/integration/test_bash_generation.py` test. Since #137 also changes the expected output of that test, I will update the expected files once that pull request is merged.

**Pull request merged**
