### PR TITLE
Print settings

### LINKED ISSUE #121: Print all settings in each generated script
Due to the inheritance model and default settings, it can sometimes be difficult to know exactly what settings were passed when instantiating a specific Jinja2 template.

To help debugging, it would be useful to print all the settings near the top of the job itself (as comments).

Not sure how easy it is to do:

https://stackoverflow.com/questions/27805445/print-all-jinja2-variables-in-a-template
https://stackoverflow.com/questions/3398850/how-to-get-a-list-of-current-variables-from-jinja-2-template

### PR DESCRIPTION
**Pull request by forsyth2**
Print settings in each generated script. Resolves #121

### CODE REVIEW

**Comment by forsyth2** [comment]
@golaz This code prints the settings for the E3SM Diags tasks. If you like this format, I can implement the same thing for the other tasks and merge.

Example output: `e3sm_diags_atm_monthly_180x360_aave_model_vs_obs_1985-2014.settings`:
```
{ 'active': True,
  'backend': 'mpl',
  'case': 'v2.LR.historical_0201',
  'cfg': '',
  'climo_diurnal_subsection': 'atm_monthly_diurnal_8xdaily_180x360_aave',
  'dc_obs_climo': '/lcrc/group/e3sm/public_html/e3sm_diags_test_data/unit_test_complete_run/obs/climatology',
  'debug': False,
  'diff_title': 'Model - Observations',
  'dry_run': False,
  'e3sm_unified': 'latest',
  'environment_commands': 'source '
                          '/home/ac.forsyth2/miniconda3/etc/profile.d/conda.sh; '
                          'conda activate e3sm_diags_env_dev_20210827',
  'grid': '180x360_aave',
  'input': '/lcrc/group/e3sm/ac.forsyth2/E3SMv2/v2.LR.historical_0201',
  'input_subdir': 'archive/atm/hist',
  'machine': 'chrysalis',
  'multiprocessing': True,
  'nodes': 1,
  'num_workers': 24,
  'obs_ts': '/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/time-series',
  'output': '/lcrc/group/e3sm/ac.forsyth2/zppy_development/issue_121.v2.LR.historical_0201',
  'output_format': ['png'],
  'output_format_subplot': ['pdf'],
  'partition': 'debug',
  'prefix': 'e3sm_diags_atm_monthly_180x360_aave_model_vs_obs_1985-2014',
  'qos': 'regular',
  'ref_final_yr': '2014',
  'ref_start_yr': '1985',
  'reference_data_path': '/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/climatology',
  'run_type': 'model_vs_obs',
  'scriptDir': '/lcrc/group/e3sm/ac.forsyth2/zppy_development/issue_121.v2.LR.historical_0201/post/scripts',
  'sets': [ 'lat_lon',
            'zonal_mean_xy',
            'zonal_mean_2d',
            'polar',
            'cosp_histogram',
            'meridional_mean_2d',
            'enso_diags',
            'qbo',
            'diurnal_cycle',
            'annual_cycle_zonal_mean',
            'streamflow'],
  'short_name': 'v2.LR.historical_0201',
  'streamflow_obs_ts': '/lcrc/group/e3sm/public_html/e3sm_diags_test_data/unit_test_complete_run/obs/time-series/',
  'subsection': 'atm_monthly_180x360_aave',
  'tag': 'model_vs_obs',
  'templateDir': '/home/ac.forsyth2/miniconda3/envs/zppy_dev_20210825/lib/python3.7/site-packages/zppy/templates',
  'ts_num_years': 10,
  'vars': 'FSNTOA,FLUT,FSNT,FLNT,FSNS,FLNS,SHFLX,QFLX,TAUX,TAUY,PRECC,PRECL,PRECSC,PRECSL,TS,TREFHT,CLDTOT,CLDHGH,CLDMED,CLDLOW,U',
  'walltime': '02:00:00',
  'www': '/lcrc/group/e3sm/public_html/diagnostic_output/ac.forsyth2/zppy_development/issue_121/',
  'year1': 1985,
  'year2': 2014,
  'years': ['1985-2014']}
(1985, 2014)
```

**Comment by forsyth2** [comment]
Note: If we keep the settings printing outside the `if not c["dry_run"]:` block (which I think would be useful as it would allow dry-run tests to produce the list of settings), then we'd also need to update the expected files for the `zppy/tests/integration/test_bash_generation.py`.

**Comment by forsyth2** [comment]
Yes, keep the printing outside the `if not c["dry_run"]:` block, so settings always print.

We may want to create a function for printing the settings at some point, but not necessary now.

`zppy/tests/integration/test_bash_generation.py` will need to have expected files updated.

**Review by golaz — APPROVED** [review]
Looks great!

**Pull request merged**
