### PR TITLE
Specify year range for e3sm_to_cmip in `ts`

### PR DESCRIPTION
**Pull request by chengzhuzhang**
To address potential problem documented here: https://github.com/E3SM-Project/zppy/issues/549#issuecomment-1955728539

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hey @forsyth2, it is great news that the tests are all passing with the new e3sm_to_cmip release. However, I still think we should consider to use specified years for `e3sm_to_cmip` as discussed earlier. Do you think we should add this fix along the new rc?

**Comment by forsyth2** [comment]
@chengzhuzhang Yes, I can implement that for the RC.

**Comment by chengzhuzhang** [comment]
> @chengzhuzhang Oh sorry, I thought this was an issue, not a PR. I will test this fix too.

Thank you!

**Comment by forsyth2** [comment]
All tests pass, merging.

**Pull request merged**
