### PR TITLE
Generalize E3SM Diags for RRM

### PR DESCRIPTION
**Pull request by golaz**
@tangq : here is the generalization for running E3SM Diags on both global and rrm (CONUS) grids. I ran a short test on your data and it seemed to work. But it would be good if you could test it more extensively.

Below is the cfg file from my test. I decided to rename the RRM grid to conus_0.23x0.31_aave to avoid confusion for different rrm settings. We could also consider dropping 'aave' from all grid names since it doesn't add much information, just make the directory paths longer.

```
[default]
input = /compyfs/dtn/tang338/20210122.beta1_01.piControlSI.northamericax4v1pg2_WC14to60E2r3_ICG.cori-knl
input_subdir = archive/atm/hist
output = /compyfs/gola749/E3SM_analysis/20210122.beta1_01.piControlSI.northamericax4v1pg2_WC14to60E2r3_ICG.cori-knl
case = 20210122.beta1_01.piControlSI.northamericax4v1pg2_WC14to60E2r3_ICG.cori-knl
www = /compyfs/www/gola749/E3SM/v2/beta
partition = short
e3sm_unified = latest

[climo]
active = True
years = "0001:0005:5",

  [[180x360_aave]]
  mapping_file = /qfs/people/tang338/E3SM/utils/PreAndPostProcessingScripts/postprocessing_bundle/v2/maps/map_northamericax4v1pg2_to_cmip6_180x360_aave.20200401.nc

  [[conus_0.23x0.31_aave]]
  grid = 'conus_0.23x0.31_aave'
  mapping_file = /qfs/people/tang338/E3SM/utils/PreAndPostProcessingScripts/postprocessing_bundle/v2/maps/map_northamericax4v1pg2_to_conus_0.23x0.31_aave.20200610.nc

[ts]
active = False

[glb]
active = False

[e3sm_diags]
active = True
short_name = '20210122.beta1_01.piControlSI.NArrm'
reference_data_path = /compyfs/e3sm_diags_data/obs_for_e3sm_diags/climatology
output_format_subplot = "pdf",
years = "0001:0005:5",

  [[180x360_aave]]
  grid = '180x360_aave'

  [[conus_0.23x0.31_aave]]
  grid = 'conus_0.23x0.31_aave'
  sets = ['lat_lon']
  cfg = "e3sm_diags/lat_lon_rrm_ERA.cfg"

[e3sm_diags_vs_model]
active = False

[mpas_analysis]
active = False

[amwg]
active = False
```

### CODE REVIEW

**Comment by tangq** [comment]
@golaz , I will test it on chrysalis with the latest RRMv2 results.

BTW, my test failed at year 17. I will create a confluence page documenting it for the v2 telecon this week.

**Comment by tangq** [comment]
Hi @golaz , my test on chrysalis shows that some RRM plots are not created: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.qtang/E3SM/v2/beta/20210212.v2_test02.piControl.naRRMpg2_WC14to60E2r3.chrysalis/e3sm_diags/conus_0.23x0.31_aave/model_vs_obs_0001-0016/viewer/lat_lon/index.html

The log file is at /lcrc/group/e3sm/ac.qtang/E3SM_simulations/20210212.v2_test02.piControl.naRRMpg2_WC14to60E2r3.chrysalis/post/scripts/e3sm_diags_conus_0.23x0.31_aave_model_vs_obs_0001-0016.o16073

I see a lot errors in the log file.

**Comment by golaz** [comment]
@tangq : I don't see anything obvious. Did you ever run E3SM Diags RRM on chrysalis?

**Comment by tangq** [comment]
@golaz , yes, this is the first time I ran e3sm_diags for RRM on chrysalis.

I changed the permissions of my home directory. You should be able to access the cfg file I used at /home/ac.qtang/E3SM/utils/zppy/20210212.v2_test02.piControl.naRRMpg2_WC14to60E2r3.chrysalis.cfg.

**Comment by chengzhuzhang** [comment]
@tangq I tried e3sm-diags with rrm.cfg files on your simulation data and found one issue: The obs directory for ERA5 was not up-to-date. After fixing these two, I get following (also I included GPCP-1DD in my .cfg to get higher resolution):https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/zhang40/model_vs_obs_0001-0016/viewer/lat_lon/index.html
I'm not sure why there were other missing figs in your run though. There a bunch of plotting errors saying:"FileExistsError: [Errno 17] File exists: '/home/ac.qtang/.local/share/cartopy/shapefiles/natural_earth/cultural'" Not sure if this is an one-off problem. I will also try running on a compute node to see if this can be re-produced.

**Comment by golaz** [comment]
@chengzhuzhang : thanks for diagnosing the problem. Should we use a different directory for obs, or did you add the missing ones? Also, should we add the new E3SM Diags cfg file that you mentioned to this PR?

**Comment by tangq** [comment]
> @chengzhuzhang : thanks for diagnosing the problem. Should we use a different directory for obs, or did you add the missing ones? Also, should we add the new E3SM Diags cfg file that you mentioned to this PR?

@golaz , I am testing the new cfg file and will post my results soon.

**Comment by chengzhuzhang** [comment]
> @chengzhuzhang : thanks for diagnosing the problem. Should we use a different directory for obs, or did you add the missing ones? Also, should we add the new E3SM Diags cfg file that you mentioned to this PR?

@golaz I updated the directory Qi has been using. Let's stick to this directory for Anvil/Chrysalis.  Yeah, we could use the[ new `.cfg` file](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/zhang40/model_vs_obs_0001-0016/prov/lat_lon_rrm.cfg) which has additional `GPCP_1DD`

**Comment by golaz** [comment]
@chengzhuzhang : if there is a new input directory for anvil/chrysalis, can we delete the old one to avoid confusing users? I think @forsyth2 may also have run into a similar problem.

**Comment by tangq** [comment]
@chengzhuzhang, thanks for the new cfg file. I've updated this PR to use it.

@golaz , my tests show that the spaces before "[#]" in the cfg file ignore that session for e3sm_diags and causes unexpected results, for example, the order of the sessions mess up. Fixed with my commit.

The result without the extra spaces (correct version):
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.qtang/E3SM/v2/beta/20210212.v2_test02.piControl.naRRMpg2_WC14to60E2r3.chrysalis/e3sm_diags/conus_0.23x0.31_aave/model_vs_obs_0001-0016/viewer/lat_lon/index.html

The result with spaces (wrong version):
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.qtang/E3SM/v2/beta/test/20210212.v2_test02.piControl.naRRMpg2_WC14to60E2r3.chrysalis/e3sm_diags/conus_0.23x0.31_aave/model_vs_obs_0001-0016/viewer/lat_lon/index.html

However, I am not sure what causes the missing figures in my previous test. Seems a one-time error.

**Review by tangq — APPROVED** [review]
The "aave" in the grid name is used to differentiate from the "bilin" ones due to different interpolation algorithms. I believe we will need it as we may use bilin maps in the future.

The e3sm_diags cfg file is essentially another cfg file required to run zppy. I feel it belongs to the test directory more than the template directory, because as the e3sm_diags RRM functions develop we will need to update it correspondingly and eventually don't need it when e3sm_diags RRM is finalized.

**Comment by golaz** [comment]
@tangq, thanks for fixing that extra space. I didn't realize that would cause an issue.

Should we further rename the cfg file: maybe to `lat_lon_conus.cfg`? We probably don't need RRM in the name (we may also want to run the diagnostics on high-res or even low-res configurations). Also, eventually, we may have diagnostics for different regions as well.

**Comment by tangq** [comment]
I agree renaming the cfg file. Or perhaps more generally rename to `e3sm_diags.cfg` and move it to the test directory as an example of how to run e3sm_diags with a customized cfg file.

**Comment by chengzhuzhang** [comment]
> @chengzhuzhang : if there is a new input directory for anvil/chrysalis, can we delete the old one to avoid confusing users? I think @forsyth2 may also have run into a similar problem.

We have been managing `/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/` as our obs path for e3sm-diags on Anvil/Chrysalis. I think the other directory mentioned is on E3SM input data server, where data are publicly available. Data folders are somehow scattered to fit our data to existing directory structure. So I'd think let's keeping using `/lcrc/soft/climate/e3sm_diags_data/obs_for_e3sm_diags/` is fine.

**Comment by golaz** [comment]
I was able to run a test successfully on chrysalis as well. On the first try, I got errors similar to @tangq; but second try was fine. So there may still be some issues with running E3SM Diags on chryalis, but I don't think they have anything to do with this PR. We can go ahead and merge.

**Pull request merged**
