### PR TITLE
Make case optional for diags

### LINKED ISSUE #522: Option to not include casename in model_vs_model diagnostic plot filename
It looks like default that casename is used to name e3sm_diags generated image file for model_vs_model comparison, for example

Here is a [model_vs_model e3sm_diags](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.wlin/E3SMv3_dev/20230929.v3alpha04-COARE.F2010.chrysalis/e3sm_diags/atm_monthly_180x360_aave_mvm/v3alpha04-COARE_vs_v3alpha04-CTL_0002-0011/viewer/) for v3alpha04 F2010 run using default vs COARE 3.0 ocean surface flux scheme.

The PRECT plot filename is [20230825.pre-v3alpha03.F2010.chrysalis-PRECT-ANN-global.png](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.wlin/E3SMv3_dev/20230929.v3alpha04-COARE.F2010.chrysalis/e3sm_diags/atm_monthly_180x360_aave_mvm/v3alpha04-COARE_vs_v3alpha04-CTL_0002-0011/lat_lon/model_vs_model/20230918.v3alpha03-ncexp1p1.F2010.chrysalis-PRECT-ANN-global.png).

The earlier version of e3sm_diags produced the plots without casename in the image filename, say, just [-PRECT-ANN-global.png](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.wlin/v3.NGD.AtmPhys/P3_ZMmicro//PSA.F2010-P3.v3atm_pre/PSA.F2010-P3.v3atm_pre_mincdnc/e3sm_diags/180x360_aave/model_vs_base_0001-0005_vs_0001-0005/lat_lon/model_vs_model/-PRECT-ANN-global.png)

For general purpose, this is not an issue. But [IICE ](https://acme-climate.atlassian.net/wiki/spaces/IPD/pages/3718709487/IICE+Interface+for+Inter-Comparison+of+E3SM+diagnostics)(comparison viewer of multiple diags), with minimum input from user specifying URL to the top viewer page alone, does not try to a determine casename associated with the diags, leaving it unable to correctly set the URL path to the image for display.

Do we already have such an option? Or was there any concern leading to the change by including casename? What if we change to not include casename in the filename, just like for model_vs_obs diags?

### PR DESCRIPTION
**Pull request by forsyth2**
Make case optional for diags. Resolves #522.

### CODE REVIEW

**Comment by forsyth2** [comment]
```
$ git grep -n "\${case}"
templates/e3sm_diags.bash:150:create_links_climo ${climo_dir_source} ${climo_dir_primary} ${case} ${Y1} ${Y2} 1
templates/e3sm_diags.bash:167:create_links_climo_diurnal ${climo_diurnal_dir_source} ${climo_diurnal_dir_primary} ${case} ${Y1} ${Y2} 3
templates/e3sm_diags.bash:254:param.test_name = '${case}'
templates/e3sm_diags.bash:479:web_dir=${www}/${case}/e3sm_diags/{{ sub }}
templates/global_time_series.bash:112:f=${www}/${case}/global_time_series
templates/global_time_series.bash:135:rsync -a --delete ${results_dir_absolute_path} ${www}/${case}/global_time_series
templates/global_time_series.bash:144:pushd ${www}/${case}/global_time_series
templates/global_time_series.bash:152:pushd ${www}/${case}/global_time_series
templates/ilamb.bash:44:mkdir -p ${model_root}/${case}
templates/ilamb.bash:45:cd ${model_root}/${case}
templates/ilamb.bash:85:web_dir=${www}/${case}/ilamb/{{ sub }}_${Y1}-${Y2}
templates/mpas_analysis.bash:325:f=${www}/${case}/mpas_analysis/${identifier}/
templates/mpas_analysis.bash:347:rsync -a --delete ${identifier}/html/ ${www}/${case}/mpas_analysis/${identifier}/
templates/mpas_analysis.bash:355:pushd ${www}/${case}/mpas_analysis/
templates/mpas_analysis.bash:363:pushd ${www}/${case}/mpas_analysis/
```

**Comment by forsyth2** [comment]
With the current changes:

Equivalent plots can be found at:
```
e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_1850-1851/viewer/lat_lon/gpcp_v32/prect-global-gpcp_v32/ann.html # With current changes
e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_1850-1851/viewer/lat_lon/gpcp_v32/prect-global-gpcp_v32/ann.html # Without these changes
```

```
# mvm files didn't generate with these changes
e3sm_diags/atm_monthly_180x360_aave_mvm/model_vs_model_1852-1853/viewer/lat_lon/model_vs_model/prect-global/ann.html # Without these changes
```

```
$ cd /lcrc/group/e3sm/ac.forsyth2/zppy_test_complete_run_output/v2.LR.historical_0201/post/scripts
$ grep -v "OK" *status
e3sm_diags_atm_monthly_180x360_aave_mvm_model_vs_model_1852-1853_vs_1850-1851.status:ERROR ()
$ cat e3sm_diags_atm_monthly_180x360_aave_mvm_model_vs_model_1852-1853_vs_1850-1851.o412745 
cp: cannot stat '/lcrc/group/e3sm/ac.forsyth2/zppy_test_complete_run_output/v2.LR.historical_0201/post/atm/180x360_aave/clim/2yr/1850_*_1851??_2??_climo.nc': No such file or directory
$ ls /lcrc/group/e3sm/ac.forsyth2/zppy_test_complete_run_output/v2.LR.historical_0201/post/atm/180x360_aave/clim/2yr/
v2.LR.historical_0201_01_185001_185101_climo.nc  v2.LR.historical_0201_07_185007_185107_climo.nc  v2.LR.historical_0201_ANN_185001_185112_climo.nc
v2.LR.historical_0201_01_185201_185301_climo.nc  v2.LR.historical_0201_07_185207_185307_climo.nc  v2.LR.historical_0201_ANN_185201_185312_climo.nc
v2.LR.historical_0201_02_185002_185102_climo.nc  v2.LR.historical_0201_08_185008_185108_climo.nc  v2.LR.historical_0201_DJF_185001_185112_climo.nc
v2.LR.historical_0201_02_185202_185302_climo.nc  v2.LR.historical_0201_08_185208_185308_climo.nc  v2.LR.historical_0201_DJF_185201_185312_climo.nc
v2.LR.historical_0201_03_185003_185103_climo.nc  v2.LR.historical_0201_09_185009_185109_climo.nc  v2.LR.historical_0201_JJA_185006_185108_climo.nc
v2.LR.historical_0201_03_185203_185303_climo.nc  v2.LR.historical_0201_09_185209_185309_climo.nc  v2.LR.historical_0201_JJA_185206_185308_climo.nc
v2.LR.historical_0201_04_185004_185104_climo.nc  v2.LR.historical_0201_10_185010_185110_climo.nc  v2.LR.historical_0201_MAM_185003_185105_climo.nc
v2.LR.historical_0201_04_185204_185304_climo.nc  v2.LR.historical_0201_10_185210_185310_climo.nc  v2.LR.historical_0201_MAM_185203_185305_climo.nc
v2.LR.historical_0201_05_185005_185105_climo.nc  v2.LR.historical_0201_11_185011_185111_climo.nc  v2.LR.historical_0201_SON_185009_185111_climo.nc
v2.LR.historical_0201_05_185205_185305_climo.nc  v2.LR.historical_0201_11_185211_185311_climo.nc  v2.LR.historical_0201_SON_185209_185311_climo.nc
v2.LR.historical_0201_06_185006_185106_climo.nc  v2.LR.historical_0201_12_185012_185112_climo.nc
v2.LR.historical_0201_06_185206_185306_climo.nc  v2.LR.historical_0201_12_185212_185312_climo.nc
```

That looks to me like we do still need the link names changed.

**Comment by chengzhuzhang** [comment]
```
if [ {{ no_case_name_in_fig }} ]; then
    ref_name=""
else
    ref_name={{ ref_name }}
fi

```
This section of code should be after creating symlinks.

**Comment by forsyth2** [comment]
@chengzhuzhang Thanks, I changed the code accordingly.

```
e3sm_diags/atm_monthly_180x360_aave_mvm/model_vs_model_1852-1853/viewer/lat_lon/model_vs_model/prect-global/ann.html # With latest changes
e3sm_diags/atm_monthly_180x360_aave_mvm/model_vs_model_1852-1853/viewer/lat_lon/model_vs_model/prect-global/ann.html # Without latest changes
```
These still match up. Neither has the case `v2.LR.historical_0201` in it though, so I guess that makes sense.

**Comment by chengzhuzhang** [comment]
@forsyth2 Looks better. But based on the request, the goal is to make case_name disappear as the default option for model-vs-model, i think we should have logic to handle this. 
`keep _mvm_case_name_in_fig` = False in `default.ini` # For small chance that users who do want to preserve the case name in model to model case, they can set it to True. 

In e3sm_diags.sh

For the e3sm_diags configuration file, add logic:
```
if run_type == "model-vs-model", and not `keep _mvm_case_name`
    `ref_name` =""
```
Let me know if it makes sense...

**Comment by forsyth2** [comment]
With latest changes (Run 3):
```
$ cd /lcrc/group/e3sm/ac.forsyth2/zppy_test_complete_run_output/v2.LR.historical_0201/post/scripts
$ grep -v "OK" *status
e3sm_diags_atm_monthly_180x360_aave_mvm_model_vs_model_1852-1853_vs_1850-1851.status:ERROR ()
$ cat e3sm_diags_atm_monthly_180x360_aave_mvm_model_vs_model_1852-1853_vs_1850-1851.o415539 
cp: cannot stat '/lcrc/group/e3sm/ac.forsyth2/zppy_test_complete_run_output/v2.LR.historical_0201/post/atm/180x360_aave/clim/2yr/1850_*_1851??_2??_climo.nc': No such file or directory
$ ls /lcrc/group/e3sm/ac.forsyth2/zppy_test_complete_run_output/v2.LR.historical_0201/post/atm/180x360_aave/clim/2yr/
v2.LR.historical_0201_01_185001_185101_climo.nc  v2.LR.historical_0201_07_185007_185107_climo.nc  v2.LR.historical_0201_ANN_185001_185112_climo.nc
v2.LR.historical_0201_01_185201_185301_climo.nc  v2.LR.historical_0201_07_185207_185307_climo.nc  v2.LR.historical_0201_ANN_185201_185312_climo.nc
v2.LR.historical_0201_02_185002_185102_climo.nc  v2.LR.historical_0201_08_185008_185108_climo.nc  v2.LR.historical_0201_DJF_185001_185112_climo.nc
v2.LR.historical_0201_02_185202_185302_climo.nc  v2.LR.historical_0201_08_185208_185308_climo.nc  v2.LR.historical_0201_DJF_185201_185312_climo.nc
v2.LR.historical_0201_03_185003_185103_climo.nc  v2.LR.historical_0201_09_185009_185109_climo.nc  v2.LR.historical_0201_JJA_185006_185108_climo.nc
v2.LR.historical_0201_03_185203_185303_climo.nc  v2.LR.historical_0201_09_185209_185309_climo.nc  v2.LR.historical_0201_JJA_185206_185308_climo.nc
v2.LR.historical_0201_04_185004_185104_climo.nc  v2.LR.historical_0201_10_185010_185110_climo.nc  v2.LR.historical_0201_MAM_185003_185105_climo.nc
v2.LR.historical_0201_04_185204_185304_climo.nc  v2.LR.historical_0201_10_185210_185310_climo.nc  v2.LR.historical_0201_MAM_185203_185305_climo.nc
v2.LR.historical_0201_05_185005_185105_climo.nc  v2.LR.historical_0201_11_185011_185111_climo.nc  v2.LR.historical_0201_SON_185009_185111_climo.nc
v2.LR.historical_0201_05_185205_185305_climo.nc  v2.LR.historical_0201_11_185211_185311_climo.nc  v2.LR.historical_0201_SON_185209_185311_climo.nc
v2.LR.historical_0201_06_185006_185106_climo.nc  v2.LR.historical_0201_12_185012_185112_climo.nc
v2.LR.historical_0201_06_185206_185306_climo.nc  v2.LR.historical_0201_12_185212_185312_climo.nc
```
The links still have the case name. I'm not sure any of the logic needeed to chang in the `.py` file. Going to try without that.

**Comment by chengzhuzhang** [comment]
I think something like below lines should be in the e3sm_diags run script, not before. Otherwise, the case name will be missing again in the links.

                if not c["keep_mvm_case_name_in_fig"]:
                    c["ref_name"] = ""

**Comment by forsyth2** [comment]
Run 7: no `ref_name` logic. I.e., how `zppy` on `main` branch currently functions.

| Path | Run 7 |
|---|---|
| model_vs_obs direct URL | `e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_1850-1851/lat_lon/GPCP_v3.2/GPCP_v3.2-PRECT-ANN-global.png` | 
| model_vs_model direct URL | `e3sm_diags/atm_monthly_180x360_aave_mvm/model_vs_model_1852-1853/lat_lon/model_vs_model/v2.LR.historical_0201-PRECT-ANN-global.png` |
| files in `post/atm/180x360_aave/clim/2yr` begin with case? | Yes |

So, to get from current functionality to expected functionality:
- We need to _add_ case name to the model-vs-obs path in all circumstances.
- We need to _remove_ case name from the model-vs-model path if `keep_mvm_case_name_in_fig=False`.
- We need to _keep_ the links in `post/atm/180x360_aave/clim/2yr` including the case name.

**Comment by chengzhuzhang** [comment]
@forsyth2 
Re: We need to add case name to the model-vs-obs path in all circumstances.
I think I need to clarify, we don't need to change anything for model-vs-obs.

**Comment by forsyth2** [comment]
> I think I need to clarify, we don't need to change anything for model-vs-obs.

@chengzhuzhang Oh, that's good then, thanks. My model-vs-obs paths don't include the case-name currently (not sure if that's just my particular configuration).

**Comment by chengzhuzhang** [comment]
> > I think I need to clarify, we don't need to change anything for model-vs-obs.
> 
> @chengzhuzhang Oh, that's good then, thanks. My model-vs-obs paths don't include the case-name currently (not sure if that's just my particular configuration).

in the path, the ref_name (i.g. GPCP_v3.2) is included. In the model vs model case shown here, the ref_name should be the reference model v2.LR.historical_0201.

**Comment by forsyth2** [comment]
>  ref_name (i.g. GPCP_v3.2) is included

Oh ok, that makes sense! Sorry, conflicting terminology case-name vs ref-name. (I mistakenly thought we wanted the case `v2.LR.historical_0201` to appear in the model-vs-obs path.)

**Comment by forsyth2** [comment]
Ok, I think I have a successful fix. Just need to check with `keep_mvm_case_name_in_fig=True`, clean up the pull request, run the tests, and merge.

| Path | Latest commit, `keep_mvm_case_name_in_fig=False` |
|---|---|
| model_vs_obs direct URL | `e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_1850-1851/lat_lon/GPCP_v3.2/GPCP_v3.2-PRECT-ANN-global.png` | 
| model_vs_model direct URL | `e3sm_diags/atm_monthly_180x360_aave_mvm/model_vs_model_1852-1853/lat_lon/model_vs_model/-PRECT-ANN-global.png` |
| files in `post/atm/180x360_aave/clim/2yr` begin with case? | Yes |

**Comment by forsyth2** [comment]
| Path | Latest commit, `keep_mvm_case_name_in_fig=True` |
|---|---|
| model_vs_obs direct URL | `e3sm_diags/atm_monthly_180x360_aave/model_vs_obs_1850-1851/lat_lon/GPCP_v3.2/GPCP_v3.2-PRECT-ANN-global.png` | 
| model_vs_model direct URL | `e3sm_diags/atm_monthly_180x360_aave_mvm/model_vs_model_1852-1853/lat_lon/model_vs_model/v2.LR.historical_0201-PRECT-ANN-global.png` |
| files in `post/atm/180x360_aave/clim/2yr` begin with case? | Yes |

Ok, that looks good too.

**Comment by wlin7** [comment]
Thank you @forsyth2 and @chengzhuzhang  for creating this option. The current IICE comparison viewer will work well with e3sm_diags generated with` keep_mvm_case_name_in_fig=False`

**Comment by chengzhuzhang** [comment]
@forsyth2 I briefly checked with @wlin7,and he suggested to have the new parameter to keep ref name True as default. This will have backward compatibility. Users who wants to use IICE can turn it to False.

**Comment by forsyth2** [comment]
> This will have backward compatibility. Users who wants to use IICE can turn it to False.

Ah ok, good idea. I will make that change and re-run the tests. Then I can make the patch release-candidate.

**Pull request merged**
