### PR TITLE
Generalize climo task

### PR DESCRIPTION
**Pull request by golaz**
Generalize climo task:

* Multiple components (eam, elm, mosart). Support for mpas is untested.
* Option to regrid or not (mapping_file = file or mapping_file = "").
* Diurnal cycle climatologies.
* Option to include/exclude variables.

### CODE REVIEW

**Comment by golaz** [comment]
@forsyth2 : I have been using this branch for several days without any incident. I'm confident it doesn't break anything and it's ready to be merged. I have not yet validated the diurnal cycle climatologies, but we can do that as part of https://github.com/E3SM-Project/zppy/pull/2

**Comment by forsyth2** [comment]
@golaz Sounds good, I'll switch my `zppy` to a copy of this branch and submit the jobs to run on my model run before I log off. If everything looks good in the morning I'll approve this PR.

**Review by forsyth2 — APPROVED** [review]
`cat *.status` on `/post/scripts` shows all `OK`. The E3SM Diags viewer seems to look alright too. 

You may want to squash your three commits into one. If you want to try that, the commands would be:
```
git fetch origin
git rebase -i origin/main
<keep the first commit as "pick",  make the second commit "f"/"fixup">
```
I tried that on a local branch and it appears to work alright; looks like `git` ignores your third commit (the merge one).

**Comment by golaz** [comment]
Thanks, @forsyth2. I did a squash and merge from here. Not sure if it's equivalent to what you suggested.

**Pull request merged**
