### PR TITLE
Add a template for high-res E3SM v1 runs 

### PR DESCRIPTION
**Pull request by xylar**
Currently, all config options are for MPAS-Analysis.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I am running tests with both E3SM-Unified 1.5.1 and 1.6.0rc3 on Cori.

The config file for the latter looks like this:
``` cfg
[default]
input = /global/cfs/cdirs/e3smdata/simulations/20190910.branch_noCNT.n825def.unc06.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG
output = /global/cscratch1/sd/xylar/test_noel_high_res_zppy/e3smu_1.6.0rc3
case = 20190910.branch_noCNT.n825def.unc06.A_WCYCL1950S_CMIP6_HR.ne120_oRRS18v3_ICG
www = /global/cfs/cdirs/e3sm/www/xylar/test_noel_high_res_zppy/e3smu_1.6.0rc3
campaign = "high_res_v1"
environment_commands = "source /global/common/software/e3sm/anaconda_envs/test_e3sm_unified_1.6.0rc3_cori-haswell.sh"

[climo]
active = False
[ts]
active = False
[e3sm_diags]
active = False
[e3sm_diags_vs_model]
active = False
[amwg]
active = False

# MPAS-Analysis
[mpas_analysis]
active = True
walltime = "04:00:00"
ts_years = "56-65",
enso_years = "56-65",
climo_years = "56-65",

[global_time_series]
active = False
```

The command to run is:
```
module load cmem
zppy -c high_res.cfg
```

**Comment by xylar** [comment]
@forsyth2, this is in draft mode until #174 is merged and I can rebase.

It will be important to document that the high res analysis will only work if someone has requested access to the `bigmem` nodes on Cori (https://docs.nersc.gov/systems/cori-largemem/#access-to-the-large-memory-nodes) and that `zppy` will only work if you first load the necessary module `module load cmem`.

**Comment by xylar** [comment]
I'm not 100% sure this should close #152.  There may be some additional analysis that needs attention and/or should be added to the `zppy/templates/high_res_v1.cfg` file.

**Comment by xylar** [comment]
@forsyth2, feel free to merge this when you're ready.  You can take out the `closes #152` message if you don't want that issue closed yet.  I will not be available for follow-up until tomorrow.

**Comment by forsyth2** [comment]
@xylar Thanks for the PR. We can leave #152 open for now.

The `cfg` file looks good to me. I'll trust your testing on Cori.

I added an integration test and documentation in this commit: https://github.com/forsyth2/zppy/commit/47a3561f9849ab5ecf478873787f10314d1fb5cd -- let me know if you'd like me to include that in this PR or just do a follow-up PR.

**Comment by xylar** [comment]
@forsyth2, I don't know how the testing works but it won't be possible to actually run the `high_res_v1` campaign on Chrysalis because the necessary nodes (and for that matter the data) are only on Cori.  If the testing is just making sure the job script gets generated correctly and isn't actually trying to run analysis, that's probably fine on Chrysalis, though.

Also, I don't personally think the tutorial is the most intuitive place to have a note about the `high_res_v1` campaign.  Would it make sense (perhaps in another PR) to add more to the documentation about the `campaign` option in general?  It would seem important to document the contents of each `cfg` file in the same way `default.ini` is documented (these will be hard to find if folk are running from E3SM-Unified).  And for `high_res_v1`, we would want something about which simulations it is appropriate for (e.g. simulations with the `oRRS18to6` ocean and sea-ice mesh).

**Comment by forsyth2** [comment]
> If the testing is just making sure the job script gets generated correctly and isn't actually trying to run analysis, that's probably fine on Chrysalis, though.

Yes, that's correct.

> Would it make sense (perhaps in another PR) to add more to the documentation about the campaign option in general?

That's a good idea. I can make a PR for that.

**Comment by xylar** [comment]
Okay, thanks for answering my questions.  I think this is fine to merge.

**Pull request merged**
