### PR TITLE
Enable revisions to old docs

### PR DESCRIPTION
**Pull request by forsyth2**
Enable revisions to old docs

### CODE REVIEW

**Comment by forsyth2** [comment]
@tomvothecoder I made changes equivalent to those found in https://github.com/E3SM-Project/e3sm_diags/pull/497, https://github.com/E3SM-Project/e3sm_diags/pull/498, and https://github.com/E3SM-Project/e3sm_diags/pull/500.

Does anything else need to be done? If not, then is the following the correct set of steps to update the v1.0.0 docs?

```
# Merge this pull request
git checkout <branch with rst changes for v1.0.0>
cd docs/
mv _build/html ../../new_v1.0.0 # Move generated docs outside of repo
git checkout <branch of gh-pages>
cd _build/html
rm -rf v1.0.0
mv ../../../new_v1.0.0 v1.0.0
# Commit, push, merge
```

**Comment by tomvothecoder** [comment]
That sounds a bit too complex for edit existing HTML builds for released tags (`v1.0.0`). You can edit the HTML files directly in `gh-pages` and push the updates (or create a separate branch from `gh-pages` to open a PR).

What I would do is:
1. Checkout `gh-pages` (or a separate branch from `gh-pages`)
  a. Much quicker to checkout `gh-pages` directly, not on your fork
  b. If you want use your fork, make sure fork `gh-pages` is aligned with `upstream/gh-pages`
2. Update/fix .html files
3. Commit, push, merge changes (PR if using separate branch)

**Review by tomvothecoder — APPROVED** [review]
LGTM

**Comment by forsyth2** [comment]
Confirming with these changes that the https://e3sm-project.github.io/zppy/_build/html/main/index.html version selector links to `main` and `v1.0.0` and that the https://e3sm-project.github.io/zppy/_build/html/v1.0.0/index.html version selector links only to `v1.0.0`.

**Pull request merged**
